apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sdlc-plugins
  title: SDLC
  description: SDLC plugin for Flowsource
  annotations:
    # For GitHub plugin
    github.com/project-slug: suremine-cts/fs-sdlc-plugins
    flowsource/github-repo-owner: suremine-cts
    flowsource/github-repo-name: fs-sdlc-plugins

    # For JIRA plugin
    # jira/project-key: SCRUM
    
    flowsource/jira-project-key: SCRUM
    flowsource/durationInDays: '90'
    flowsource/jira-storypoint-field: '#notapplicable'

    # For Jenkins plugin
    # flowsource/jenkins-pipelines: fs-sdlc/main
  tags:
    - github
    - jira
    - jenkins
    - flowsource
  links:
    - url: https://github.com/cts-suresh/fs-sdlc-plugins
      title: GitHub Repo
      icon: github
    - url: https://suremine.atlassian.net/browse/SCRUM
      title: Jira Project
      icon: dashboard
spec:
  type: service
  lifecycle: experimental
  owner: group:default/platform-team
  system: flowsource
